/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

#ifndef _ASN_CONSTANT_H
#define _ASN_CONSTANT_H

#ifdef __cplusplus
extern "C" {
#endif

#define maxE1APid (65535)
#define maxF1APid (4)
#define maxEARFCN (65535)
#define maxNRARFCN (3279165)
#define maxnoofNrCellBands (32)
#define maxnoofMessages (65535)
#define maxnoofE2InfoChanges (65535)
#define maxnoofUEInfoChanges (65535)
#define maxnoofRRCstate (8)
#define maxnoofParametersToReport (65535)
#define maxnoofPolicyConditions (65535)
#define maxnoofAssociatedRANParameters (65535)
#define maxnoofUEID (65535)
#define maxnoofCellID (65535)
#define maxnoofRANOutcomeParameters (255)
#define maxnoofParametersinStructure (65535)
#define maxnoofItemsinList (65535)
#define maxnoofUEInfo (65535)
#define maxnoofCellInfo (65535)
#define maxnoofUEeventInfo (65535)
#define maxnoofRANparamTest (255)
#define maxnoofNeighbourCell (65535)
#define maxnoofRICStyles (63)
#define maxnoofCallProcessTypes (65535)
#define maxnoofCallProcessBreakpoints (65535)
#define maxnoofInsertIndication (65535)
#define maxnoofControlAction (65535)
#define maxnoofPolicyAction (65535)
#define maxnoofInsertIndicationActions (63)
#define maxnoofMulCtrlActions (63)


#ifdef __cplusplus
}
#endif

#endif /* _ASN_CONSTANT_H */
