/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-COMMON-IEs"
 * 	found in "e2sm-v02.01.asn1"
 * 	`asn1c -fcompound-names -findirect-choice -fincludes-quoted -fno-include-deps -gen-PER -no-gen-example`
 */

#ifndef	_E_UTRA_ARFCN_H_
#define	_E_UTRA_ARFCN_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* E-UTRA-ARFCN */
typedef long	 E_UTRA_ARFCN_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_E_UTRA_ARFCN_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_E_UTRA_ARFCN;
asn_struct_free_f E_UTRA_ARFCN_free;
asn_struct_print_f E_UTRA_ARFCN_print;
asn_constr_check_f E_UTRA_ARFCN_constraint;
ber_type_decoder_f E_UTRA_ARFCN_decode_ber;
der_type_encoder_f E_UTRA_ARFCN_encode_der;
xer_type_decoder_f E_UTRA_ARFCN_decode_xer;
xer_type_encoder_f E_UTRA_ARFCN_encode_xer;
oer_type_decoder_f E_UTRA_ARFCN_decode_oer;
oer_type_encoder_f E_UTRA_ARFCN_encode_oer;
per_type_decoder_f E_UTRA_ARFCN_decode_uper;
per_type_encoder_f E_UTRA_ARFCN_encode_uper;
per_type_decoder_f E_UTRA_ARFCN_decode_aper;
per_type_encoder_f E_UTRA_ARFCN_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _E_UTRA_ARFCN_H_ */
#include "asn_internal.h"
