/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "e2sm-rc-v01.02.03.asn1"
 * 	`asn1c -fcompound-names -findirect-choice -fincludes-quoted -fno-include-deps -gen-PER -no-gen-example`
 */

#include "E2SM-RC-EventTrigger-Format5.h"

#include "EventTrigger-UE-Info.h"
#include "EventTrigger-Cell-Info.h"
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_onDemand_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_onDemand_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  0,  0,  0,  0 }	/* (0..0,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_onDemand_value2enum_2[] = {
	{ 0,	4,	"true" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_onDemand_enum2value_2[] = {
	0	/* true(0) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_onDemand_specs_2 = {
	asn_MAP_onDemand_value2enum_2,	/* "tag" => N; sorted by tag */
	asn_MAP_onDemand_enum2value_2,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	2,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_onDemand_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_onDemand_2 = {
	"onDemand",
	"onDemand",
	&asn_OP_NativeEnumerated,
	asn_DEF_onDemand_tags_2,
	sizeof(asn_DEF_onDemand_tags_2)
		/sizeof(asn_DEF_onDemand_tags_2[0]) - 1, /* 1 */
	asn_DEF_onDemand_tags_2,	/* Same as above */
	sizeof(asn_DEF_onDemand_tags_2)
		/sizeof(asn_DEF_onDemand_tags_2[0]), /* 2 */
	{ &asn_OER_type_onDemand_constr_2, &asn_PER_type_onDemand_constr_2, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_onDemand_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_E2SM_RC_EventTrigger_Format5_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_RC_EventTrigger_Format5, onDemand),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_onDemand_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"onDemand"
		},
	{ ATF_POINTER, 2, offsetof(struct E2SM_RC_EventTrigger_Format5, associatedUEInfo),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EventTrigger_UE_Info,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"associatedUEInfo"
		},
	{ ATF_POINTER, 1, offsetof(struct E2SM_RC_EventTrigger_Format5, associatedCellInfo),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EventTrigger_Cell_Info,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"associatedCellInfo"
		},
};
static const int asn_MAP_E2SM_RC_EventTrigger_Format5_oms_1[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_E2SM_RC_EventTrigger_Format5_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_E2SM_RC_EventTrigger_Format5_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* onDemand */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* associatedUEInfo */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* associatedCellInfo */
};
asn_SEQUENCE_specifics_t asn_SPC_E2SM_RC_EventTrigger_Format5_specs_1 = {
	sizeof(struct E2SM_RC_EventTrigger_Format5),
	offsetof(struct E2SM_RC_EventTrigger_Format5, _asn_ctx),
	asn_MAP_E2SM_RC_EventTrigger_Format5_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_E2SM_RC_EventTrigger_Format5_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_E2SM_RC_EventTrigger_Format5 = {
	"E2SM-RC-EventTrigger-Format5",
	"E2SM-RC-EventTrigger-Format5",
	&asn_OP_SEQUENCE,
	asn_DEF_E2SM_RC_EventTrigger_Format5_tags_1,
	sizeof(asn_DEF_E2SM_RC_EventTrigger_Format5_tags_1)
		/sizeof(asn_DEF_E2SM_RC_EventTrigger_Format5_tags_1[0]), /* 1 */
	asn_DEF_E2SM_RC_EventTrigger_Format5_tags_1,	/* Same as above */
	sizeof(asn_DEF_E2SM_RC_EventTrigger_Format5_tags_1)
		/sizeof(asn_DEF_E2SM_RC_EventTrigger_Format5_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_E2SM_RC_EventTrigger_Format5_1,
	3,	/* Elements count */
	&asn_SPC_E2SM_RC_EventTrigger_Format5_specs_1	/* Additional specs */
};

