/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "e2sm-rc-v01.02.03.asn1"
 * 	`asn1c -fcompound-names -findirect-choice -fincludes-quoted -fno-include-deps -gen-PER -no-gen-example`
 */

#include "EventTrigger-UE-Info-Item-Choice-Individual.h"

#include "RANParameter-Testing.h"
asn_TYPE_member_t asn_MBR_EventTrigger_UE_Info_Item_Choice_Individual_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EventTrigger_UE_Info_Item_Choice_Individual, ueID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UEID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ueID"
		},
	{ ATF_POINTER, 1, offsetof(struct EventTrigger_UE_Info_Item_Choice_Individual, ranParameterTesting),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANParameter_Testing,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ranParameterTesting"
		},
};
static const int asn_MAP_EventTrigger_UE_Info_Item_Choice_Individual_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_EventTrigger_UE_Info_Item_Choice_Individual_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_EventTrigger_UE_Info_Item_Choice_Individual_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ueID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* ranParameterTesting */
};
asn_SEQUENCE_specifics_t asn_SPC_EventTrigger_UE_Info_Item_Choice_Individual_specs_1 = {
	sizeof(struct EventTrigger_UE_Info_Item_Choice_Individual),
	offsetof(struct EventTrigger_UE_Info_Item_Choice_Individual, _asn_ctx),
	asn_MAP_EventTrigger_UE_Info_Item_Choice_Individual_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_EventTrigger_UE_Info_Item_Choice_Individual_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_EventTrigger_UE_Info_Item_Choice_Individual = {
	"EventTrigger-UE-Info-Item-Choice-Individual",
	"EventTrigger-UE-Info-Item-Choice-Individual",
	&asn_OP_SEQUENCE,
	asn_DEF_EventTrigger_UE_Info_Item_Choice_Individual_tags_1,
	sizeof(asn_DEF_EventTrigger_UE_Info_Item_Choice_Individual_tags_1)
		/sizeof(asn_DEF_EventTrigger_UE_Info_Item_Choice_Individual_tags_1[0]), /* 1 */
	asn_DEF_EventTrigger_UE_Info_Item_Choice_Individual_tags_1,	/* Same as above */
	sizeof(asn_DEF_EventTrigger_UE_Info_Item_Choice_Individual_tags_1)
		/sizeof(asn_DEF_EventTrigger_UE_Info_Item_Choice_Individual_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_EventTrigger_UE_Info_Item_Choice_Individual_1,
	2,	/* Elements count */
	&asn_SPC_EventTrigger_UE_Info_Item_Choice_Individual_specs_1	/* Additional specs */
};

