/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "e2sm-rc-v01.02.03.asn1"
 * 	`asn1c -fcompound-names -findirect-choice -fincludes-quoted -fno-include-deps -gen-PER -no-gen-example`
 */

#include "MessageType-Choice-RRC.h"

asn_TYPE_member_t asn_MBR_MessageType_Choice_RRC_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MessageType_Choice_RRC, rRC_Message),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRC_MessageID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rRC-Message"
		},
};
static const ber_tlv_tag_t asn_DEF_MessageType_Choice_RRC_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_MessageType_Choice_RRC_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* rRC-Message */
};
asn_SEQUENCE_specifics_t asn_SPC_MessageType_Choice_RRC_specs_1 = {
	sizeof(struct MessageType_Choice_RRC),
	offsetof(struct MessageType_Choice_RRC, _asn_ctx),
	asn_MAP_MessageType_Choice_RRC_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_MessageType_Choice_RRC = {
	"MessageType-Choice-RRC",
	"MessageType-Choice-RRC",
	&asn_OP_SEQUENCE,
	asn_DEF_MessageType_Choice_RRC_tags_1,
	sizeof(asn_DEF_MessageType_Choice_RRC_tags_1)
		/sizeof(asn_DEF_MessageType_Choice_RRC_tags_1[0]), /* 1 */
	asn_DEF_MessageType_Choice_RRC_tags_1,	/* Same as above */
	sizeof(asn_DEF_MessageType_Choice_RRC_tags_1)
		/sizeof(asn_DEF_MessageType_Choice_RRC_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_MessageType_Choice_RRC_1,
	1,	/* Elements count */
	&asn_SPC_MessageType_Choice_RRC_specs_1	/* Additional specs */
};

