/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "e2sm-rc-v01.02.03.asn1"
 * 	`asn1c -fcompound-names -findirect-choice -fincludes-quoted -fno-include-deps -gen-PER -no-gen-example`
 */

#ifndef	_NeighborCell_Item_H_
#define	_NeighborCell_Item_H_


#include "asn_application.h"

/* Including external dependencies */
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NeighborCell_Item_PR {
	NeighborCell_Item_PR_NOTHING,	/* No components present */
	NeighborCell_Item_PR_ranType_Choice_NR,
	NeighborCell_Item_PR_ranType_Choice_EUTRA
	/* Extensions may appear below */
	
} NeighborCell_Item_PR;

/* Forward declarations */
struct NeighborCell_Item_Choice_NR;
struct NeighborCell_Item_Choice_E_UTRA;

/* NeighborCell-Item */
typedef struct NeighborCell_Item {
	NeighborCell_Item_PR present;
	union NeighborCell_Item_u {
		struct NeighborCell_Item_Choice_NR	*ranType_Choice_NR;
		struct NeighborCell_Item_Choice_E_UTRA	*ranType_Choice_EUTRA;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NeighborCell_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NeighborCell_Item;
extern asn_CHOICE_specifics_t asn_SPC_NeighborCell_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_NeighborCell_Item_1[2];
extern asn_per_constraints_t asn_PER_type_NeighborCell_Item_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NeighborCell_Item_H_ */
#include "asn_internal.h"
