/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "e2sm-rc-v01.02.03.asn1"
 * 	`asn1c -fcompound-names -findirect-choice -fincludes-quoted -fno-include-deps -gen-PER -no-gen-example`
 */

#include "NeighborCell-List.h"

#include "NeighborCell-Item.h"
static asn_oer_constraints_t asn_OER_type_NeighborCell_List_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
asn_per_constraints_t asn_PER_type_NeighborCell_List_constr_1 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_NeighborCell_List_1[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_NeighborCell_Item,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_NeighborCell_List_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_NeighborCell_List_specs_1 = {
	sizeof(struct NeighborCell_List),
	offsetof(struct NeighborCell_List, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
asn_TYPE_descriptor_t asn_DEF_NeighborCell_List = {
	"NeighborCell-List",
	"NeighborCell-List",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_NeighborCell_List_tags_1,
	sizeof(asn_DEF_NeighborCell_List_tags_1)
		/sizeof(asn_DEF_NeighborCell_List_tags_1[0]), /* 1 */
	asn_DEF_NeighborCell_List_tags_1,	/* Same as above */
	sizeof(asn_DEF_NeighborCell_List_tags_1)
		/sizeof(asn_DEF_NeighborCell_List_tags_1[0]), /* 1 */
	{ &asn_OER_type_NeighborCell_List_constr_1, &asn_PER_type_NeighborCell_List_constr_1, SEQUENCE_OF_constraint },
	asn_MBR_NeighborCell_List_1,
	1,	/* Single element */
	&asn_SPC_NeighborCell_List_specs_1	/* Additional specs */
};

