/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "e2sm-rc-v01.02.03.asn1"
 * 	`asn1c -fcompound-names -findirect-choice -fincludes-quoted -fno-include-deps -gen-PER -no-gen-example`
 */

#ifndef	_RANParameter_Definition_Choice_LIST_H_
#define	_RANParameter_Definition_Choice_LIST_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RANParameter_Definition_Choice_LIST_Item;

/* RANParameter-Definition-Choice-LIST */
typedef struct RANParameter_Definition_Choice_LIST {
	struct RANParameter_Definition_Choice_LIST__ranParameter_List {
		A_SEQUENCE_OF(struct RANParameter_Definition_Choice_LIST_Item) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ranParameter_List;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANParameter_Definition_Choice_LIST_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RANParameter_Definition_Choice_LIST;
extern asn_SEQUENCE_specifics_t asn_SPC_RANParameter_Definition_Choice_LIST_specs_1;
extern asn_TYPE_member_t asn_MBR_RANParameter_Definition_Choice_LIST_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _RANParameter_Definition_Choice_LIST_H_ */
#include "asn_internal.h"
