/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "e2sm-rc-v01.02.03.asn1"
 * 	`asn1c -fcompound-names -findirect-choice -fincludes-quoted -fno-include-deps -gen-PER -no-gen-example`
 */

#ifndef	_RANParameter_ValueType_Choice_ElementFalse_H_
#define	_RANParameter_ValueType_Choice_ElementFalse_H_


#include "asn_application.h"

/* Including external dependencies */
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RANParameter_Value;

/* RANParameter-ValueType-Choice-ElementFalse */
typedef struct RANParameter_ValueType_Choice_ElementFalse {
	struct RANParameter_Value	*ranParameter_value;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANParameter_ValueType_Choice_ElementFalse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RANParameter_ValueType_Choice_ElementFalse;
extern asn_SEQUENCE_specifics_t asn_SPC_RANParameter_ValueType_Choice_ElementFalse_specs_1;
extern asn_TYPE_member_t asn_MBR_RANParameter_ValueType_Choice_ElementFalse_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _RANParameter_ValueType_Choice_ElementFalse_H_ */
#include "asn_internal.h"
