/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "e2sm-rc-v01.02.03.asn1"
 * 	`asn1c -fcompound-names -findirect-choice -fincludes-quoted -fno-include-deps -gen-PER -no-gen-example`
 */

#include "RANParameter-Testing-Item.h"

#include "RANParameter-Testing-Item-Choice-List.h"
#include "RANParameter-Testing-Item-Choice-Structure.h"
#include "RANParameter-Testing-Item-Choice-ElementTrue.h"
#include "RANParameter-Testing-Item-Choice-ElementFalse.h"
static asn_oer_constraints_t asn_OER_type_ranParameter_Type_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_ranParameter_Type_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  3 }	/* (0..3,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_ranParameter_Type_3[] = {
	{ ATF_POINTER, 0, offsetof(struct RANParameter_Testing_Item__ranParameter_Type, choice.ranP_Choice_List),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANParameter_Testing_Item_Choice_List,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ranP-Choice-List"
		},
	{ ATF_POINTER, 0, offsetof(struct RANParameter_Testing_Item__ranParameter_Type, choice.ranP_Choice_Structure),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANParameter_Testing_Item_Choice_Structure,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ranP-Choice-Structure"
		},
	{ ATF_POINTER, 0, offsetof(struct RANParameter_Testing_Item__ranParameter_Type, choice.ranP_Choice_ElementTrue),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANParameter_Testing_Item_Choice_ElementTrue,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ranP-Choice-ElementTrue"
		},
	{ ATF_POINTER, 0, offsetof(struct RANParameter_Testing_Item__ranParameter_Type, choice.ranP_Choice_ElementFalse),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANParameter_Testing_Item_Choice_ElementFalse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ranP-Choice-ElementFalse"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ranParameter_Type_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ranP-Choice-List */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ranP-Choice-Structure */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ranP-Choice-ElementTrue */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* ranP-Choice-ElementFalse */
};
static asn_CHOICE_specifics_t asn_SPC_ranParameter_Type_specs_3 = {
	sizeof(struct RANParameter_Testing_Item__ranParameter_Type),
	offsetof(struct RANParameter_Testing_Item__ranParameter_Type, _asn_ctx),
	offsetof(struct RANParameter_Testing_Item__ranParameter_Type, present),
	sizeof(((struct RANParameter_Testing_Item__ranParameter_Type *)0)->present),
	asn_MAP_ranParameter_Type_tag2el_3,
	4,	/* Count of tags in the map */
	0, 0,
	4	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ranParameter_Type_3 = {
	"ranParameter-Type",
	"ranParameter-Type",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_ranParameter_Type_constr_3, &asn_PER_type_ranParameter_Type_constr_3, CHOICE_constraint },
	asn_MBR_ranParameter_Type_3,
	4,	/* Elements count */
	&asn_SPC_ranParameter_Type_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RANParameter_Testing_Item_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RANParameter_Testing_Item, ranParameter_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANParameter_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ranParameter-ID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANParameter_Testing_Item, ranParameter_Type),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ranParameter_Type_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ranParameter-Type"
		},
};
static const ber_tlv_tag_t asn_DEF_RANParameter_Testing_Item_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RANParameter_Testing_Item_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ranParameter-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* ranParameter-Type */
};
asn_SEQUENCE_specifics_t asn_SPC_RANParameter_Testing_Item_specs_1 = {
	sizeof(struct RANParameter_Testing_Item),
	offsetof(struct RANParameter_Testing_Item, _asn_ctx),
	asn_MAP_RANParameter_Testing_Item_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RANParameter_Testing_Item = {
	"RANParameter-Testing-Item",
	"RANParameter-Testing-Item",
	&asn_OP_SEQUENCE,
	asn_DEF_RANParameter_Testing_Item_tags_1,
	sizeof(asn_DEF_RANParameter_Testing_Item_tags_1)
		/sizeof(asn_DEF_RANParameter_Testing_Item_tags_1[0]), /* 1 */
	asn_DEF_RANParameter_Testing_Item_tags_1,	/* Same as above */
	sizeof(asn_DEF_RANParameter_Testing_Item_tags_1)
		/sizeof(asn_DEF_RANParameter_Testing_Item_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RANParameter_Testing_Item_1,
	2,	/* Elements count */
	&asn_SPC_RANParameter_Testing_Item_specs_1	/* Additional specs */
};

