/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-Bouncer-IEs"
 *      found in "/home/ubuntu/ASN-Defns/e2sm-Bouncer-v002.asn"
 * 	`asn1c -fno-include-deps -fcompound-names -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_B_ControlCommand_H_
#define	_B_ControlCommand_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum B_ControlCommand {
	B_ControlCommand_addition	= 0,
	B_ControlCommand_deletion	= 1
	/*
	 * Enumeration is extensible
	 */
} e_B_ControlCommand;

/* B-ControlCommand */
typedef long	 B_ControlCommand_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_B_ControlCommand;
asn_struct_free_f B_ControlCommand_free;
asn_struct_print_f B_ControlCommand_print;
asn_constr_check_f B_ControlCommand_constraint;
ber_type_decoder_f B_ControlCommand_decode_ber;
der_type_encoder_f B_ControlCommand_encode_der;
xer_type_decoder_f B_ControlCommand_decode_xer;
xer_type_encoder_f B_ControlCommand_encode_xer;
per_type_decoder_f B_ControlCommand_decode_uper;
per_type_encoder_f B_ControlCommand_encode_uper;
per_type_decoder_f B_ControlCommand_decode_aper;
per_type_encoder_f B_ControlCommand_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _B_ControlCommand_H_ */
#include <asn_internal.h>
