/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-Bouncer-IEs"
 *      found in "/home/ubuntu/ASN-Defns/e2sm-Bouncer-v002.asn"
 * 	`asn1c -fno-include-deps -fcompound-names -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_B_Header_H_
#define	_B_Header_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* B-Header */
typedef long	B_Header_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_B_Header;
asn_struct_free_f B_Header_free;
asn_struct_print_f B_Header_print;
asn_constr_check_f B_Header_constraint;
ber_type_decoder_f B_Header_decode_ber;
der_type_encoder_f B_Header_encode_der;
xer_type_decoder_f B_Header_decode_xer;
xer_type_encoder_f B_Header_encode_xer;
per_type_decoder_f B_Header_decode_uper;
per_type_encoder_f B_Header_encode_uper;
per_type_decoder_f B_Header_decode_aper;
per_type_encoder_f B_Header_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _B_Header_H_ */
#include <asn_internal.h>
