################################################################################
#   Copyright (c) 2019 AT&T Intellectual Property.                             #
#   Copyright (c) 2019 Nokia.                                                  #
#                                                                              #
#   Licensed under the Apache License, Version 2.0 (the "License");            #
#   you may not use this file except in compliance with the License.           #
#   You may obtain a copy of the License at                                    #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
#   Unless required by applicable law or agreed to in writing, software        #
#   distributed under the License is distributed on an "AS IS" BASIS,          #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
#   See the License for the specific language governing permissions and        #
#   limitations under the License.                                             #
################################################################################
{{- $topCtx :=  . }} 
{{- range keys .Values.e2term }} 
{{- $key := . }} 
{{- with index $topCtx.Values.e2term . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.servicename.e2term.prometheus" $topCtx }}-{{ $key }}
  namespace: {{ include "common.namespace.platform" $topCtx }}
  labels:
    app: {{ include "common.namespace.platform" $topCtx }}-{{ include "common.name.e2term" $topCtx }}-{{ $key }}
    chart: {{ $topCtx.Chart.Name }}-{{ $topCtx.Chart.Version | replace "+" "_" }}
    release: {{ $topCtx.Release.Name }}
    heritage: {{ $topCtx.Release.Service }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: {{ include "common.serviceport.e2term.prometheus" $topCtx | quote }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "common.serviceport.e2term.prometheus" $topCtx }}
      protocol: "TCP"
      targetPort: "prmts-{{ $key }}"
      name: "prmts-{{ $key }}"
  selector:
      app: {{ include "common.namespace.platform" $topCtx }}-{{ include "common.name.e2term" $topCtx }}-{{ $key }}
      release: {{ $topCtx.Release.Name }}
{{- end }}
{{- end }}
